//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsMarathon
    {
        public int ID { get; set; }
        public int ID_Marathon { get; set; }
        public int ID_User { get; set; }
        public System.DateTime Time { get; set; }
        public System.DateTime GeneralTime { get; set; }
        public int MyPlace { get; set; }
        public string Marathon { get; set; }
        public string User { get; set; }
    }
}
